// Quick CS/programming trivia shown to the user while a video generates.
export const FLASHCARDS = [
  { q: 'What is an API?', a: 'A set of rules that lets different pieces of software talk to each other.' },
  { q: 'Stack vs. Heap?', a: 'Stack: fast, fixed-size, used for function calls. Heap: flexible, manually managed memory.' },
  { q: 'What is Big O notation?', a: "A way to describe how an algorithm's runtime grows as the input gets bigger." },
  { q: 'What is recursion?', a: 'A function that calls itself to solve smaller instances of the same problem.' },
  { q: 'What does DRY stand for?', a: "Don't Repeat Yourself — avoid duplicating logic." },
  { q: 'What is a hash table?', a: 'A data structure that maps keys to values for near-instant lookup.' },
  { q: 'Big O of binary search?', a: 'O(log n) — it halves the search space each step.' },
  { q: 'What is a closure?', a: 'A function that remembers variables from the scope it was created in.' },
  { q: 'What is REST?', a: 'An architectural style for APIs built on standard HTTP methods like GET and POST.' },
  { q: 'What is a race condition?', a: 'When multiple processes access shared data at once, causing unpredictable results.' },
  { q: 'What is Git?', a: 'A version control system for tracking changes to code over time.' },
  { q: 'What is a linked list?', a: 'A sequence of nodes where each one points to the next.' },
  { q: 'HTTP vs. HTTPS?', a: 'HTTPS is HTTP with encryption (TLS) added on top.' },
  { q: 'Big O of a hash table lookup?', a: 'O(1) on average — constant time.' },
  { q: 'What is a compiler?', a: 'A program that translates source code into machine code before it runs.' },
  { q: 'What is an interpreter?', a: 'A program that executes code directly, line by line, with no separate compile step.' },
  { q: 'What is a null reference error?', a: 'An error from trying to use a reference that points to nothing.' },
  { q: 'What does CPU stand for?', a: 'Central Processing Unit — the chip that executes instructions.' },
  { q: 'What is a boolean?', a: 'A data type with exactly two possible values: true or false.' },
  { q: 'What is an array index?', a: "A number giving an element's position in an array, usually starting at 0." },
  { q: 'What is a variable?', a: 'A named container that holds a value your program can read or change.' },
  { q: 'What is a function?', a: 'A reusable block of code that performs a task and can return a value.' },
  { q: 'What is an object (OOP)?', a: 'An instance of a class, bundling data and the functions that operate on it.' },
  { q: 'What is inheritance?', a: 'A way for one class to reuse and extend the behavior of another.' },
  { q: 'What is polymorphism?', a: 'The ability for different types to be used through the same interface.' },
  { q: 'What is encapsulation?', a: "Hiding an object's internal details and exposing only what's needed." },
  { q: 'What is an abstract class?', a: 'A class that cannot be instantiated directly and is meant to be extended.' },
  { q: 'What is an interface?', a: 'A contract that defines methods a class must implement, without the logic.' },
  { q: 'What is a queue?', a: 'A FIFO data structure — first item added is the first one removed.' },
  { q: 'What is a stack?', a: 'A LIFO data structure — last item added is the first one removed.' },
  { q: 'What is a binary tree?', a: 'A tree where each node has at most two children.' },
  { q: 'What is a binary search tree?', a: 'A binary tree where left children are smaller and right children are larger.' },
  { q: 'What is a graph (data structure)?', a: 'A set of nodes connected by edges, used to model relationships or networks.' },
  { q: 'Big O of a linked list search?', a: 'O(n) — you may have to walk every node.' },
  { q: 'Big O of accessing an array by index?', a: 'O(1) — constant time, direct memory offset.' },
  { q: 'Big O of bubble sort?', a: 'O(n²) in the worst case — nested comparisons over the list.' },
  { q: 'Big O of merge sort?', a: 'O(n log n) — splits the list and merges sorted halves.' },
  { q: 'Big O of quicksort (average case)?', a: 'O(n log n), though O(n²) in the worst case with bad pivots.' },
  { q: 'What is a pointer?', a: 'A variable that stores the memory address of another value.' },
  { q: 'What is garbage collection?', a: 'Automatic reclaiming of memory no longer referenced by a program.' },
  { q: 'What is a memory leak?', a: "Memory that's no longer needed but never freed, wasting resources over time." },
  { q: 'What is a segmentation fault?', a: 'A crash caused by accessing memory the program has no permission to use.' },
  { q: 'What is type coercion?', a: 'Automatic conversion of a value from one data type to another.' },
  { q: 'Static vs. dynamic typing?', a: 'Static checks types at compile time; dynamic checks them at runtime.' },
  { q: 'What is a tuple?', a: 'An ordered, typically immutable collection of values.' },
  { q: 'What is a dictionary / map?', a: 'A collection of key-value pairs offering fast lookup by key.' },
  { q: 'What is a set (data structure)?', a: 'A collection of unique values with no duplicates.' },
  { q: 'What is immutability?', a: 'A property where a value cannot be changed after it is created.' },
  { q: 'What is a lambda function?', a: 'A small, anonymous function defined inline without a name.' },
  { q: 'What is a higher-order function?', a: 'A function that takes another function as an argument or returns one.' },
  { q: 'What is pure function?', a: 'A function with no side effects that always returns the same output for the same input.' },
  { q: 'What is a side effect (programming)?', a: "Any change a function makes outside its own scope, like modifying a global." },
  { q: 'What is scope (variables)?', a: 'The region of code where a variable is accessible.' },
  { q: 'What is a global variable?', a: 'A variable accessible from anywhere in the program.' },
  { q: 'What is dependency injection?', a: "Supplying an object's dependencies from outside rather than creating them internally." },
  { q: 'What is a design pattern?', a: 'A reusable, general solution to a common software design problem.' },
  { q: 'What is the singleton pattern?', a: 'A pattern ensuring a class has only one instance, globally accessible.' },
  { q: 'What is the observer pattern?', a: 'A pattern where objects subscribe to and get notified of events from another object.' },
  { q: 'What is MVC?', a: 'Model-View-Controller — a pattern separating data, UI, and control logic.' },
  { q: 'What is an algorithm?', a: 'A step-by-step procedure for solving a problem or completing a task.' },
  { q: 'What is dynamic programming?', a: 'Solving problems by breaking them into overlapping subproblems and caching results.' },
  { q: 'What is memoization?', a: "Caching a function's results so repeated calls with the same input are instant." },
  { q: 'What is a greedy algorithm?', a: 'An algorithm that makes the locally best choice at each step, hoping for a global optimum.' },
  { q: 'What is backtracking?', a: 'Trying a solution, and undoing it to try another if it fails.' },
  { q: 'What is depth-first search?', a: 'A traversal that explores as far as possible down one path before backtracking.' },
  { q: 'What is breadth-first search?', a: 'A traversal that explores all neighbors at the current depth before going deeper.' },
  { q: 'What is a hash collision?', a: 'When two different keys map to the same slot in a hash table.' },
  { q: 'What is TCP?', a: 'A reliable, ordered, connection-based protocol for sending data over a network.' },
  { q: 'What is UDP?', a: 'A fast, connectionless protocol that sends data without guaranteeing delivery or order.' },
  { q: 'What is DNS?', a: 'The system that translates domain names into IP addresses.' },
  { q: 'What is an IP address?', a: "A numeric label identifying a device's location on a network." },
  { q: 'What is a port (networking)?', a: 'A number identifying a specific process or service on a device.' },
  { q: 'What is a firewall?', a: 'A system that filters network traffic based on security rules.' },
  { q: 'What is latency?', a: 'The time delay between a request being sent and a response arriving.' },
  { q: 'What is bandwidth?', a: 'The maximum amount of data that can be transferred over a connection per second.' },
  { q: 'What is a load balancer?', a: 'A system that distributes incoming traffic across multiple servers.' },
  { q: 'What is caching?', a: 'Storing a copy of data somewhere faster to access, to speed up future requests.' },
  { q: 'What is a CDN?', a: 'A network of distributed servers that deliver content from a location near the user.' },
  { q: 'What is an HTTP status code 404?', a: 'Not Found — the requested resource does not exist on the server.' },
  { q: 'What is an HTTP status code 500?', a: 'Internal Server Error — something went wrong on the server side.' },
  { q: 'GET vs. POST?', a: 'GET retrieves data via the URL; POST sends data in the request body, often to create or update.' },
  { q: 'What is JSON?', a: 'A lightweight, human-readable text format for structuring and exchanging data.' },
  { q: 'What is an API endpoint?', a: 'A specific URL where an API can be accessed for a given operation.' },
  { q: 'What is authentication?', a: 'Verifying who a user is, typically via credentials.' },
  { q: 'What is authorization?', a: 'Determining what an authenticated user is allowed to do.' },
  { q: 'What is a token (auth)?', a: 'A piece of data proving a user is authenticated, used instead of resending credentials.' },
  { q: 'What is OAuth?', a: 'A standard protocol that lets apps get limited access to a user account on another service.' },
  { q: 'What is a database index?', a: 'A structure that speeds up lookups on a table at the cost of extra storage.' },
  { q: 'What is a primary key?', a: 'A column (or set of columns) that uniquely identifies each row in a table.' },
  { q: 'What is a foreign key?', a: 'A column that references the primary key of another table, linking the two.' },
  { q: 'What is normalization (databases)?', a: 'Organizing tables to reduce data duplication and improve integrity.' },
  { q: 'SQL vs. NoSQL?', a: 'SQL databases use structured tables and schemas; NoSQL databases store flexible, often schema-less data.' },
  { q: 'What is a JOIN (SQL)?', a: 'An operation that combines rows from two or more tables based on a related column.' },
  { q: 'What is a transaction (databases)?', a: 'A group of operations that all succeed together or all fail together.' },
  { q: 'What does ACID stand for?', a: 'Atomicity, Consistency, Isolation, Durability — guarantees for reliable database transactions.' },
  { q: 'What is a deadlock?', a: 'A situation where two or more processes wait forever for each other to release resources.' },
  { q: 'What is multithreading?', a: 'Running multiple threads within a single process to do work concurrently.' },
  { q: 'What is a thread?', a: 'The smallest unit of execution that can be scheduled by an operating system.' },
  { q: 'What is a process (OS)?', a: 'An independent running instance of a program with its own memory space.' },
  { q: 'What is an operating system?', a: 'Software that manages hardware and provides services for other programs to run.' },
  { q: 'What is virtual memory?', a: "An abstraction that lets a program use more memory than physically exists, via disk swapping." },
  { q: 'What is cache (CPU)?', a: 'A small, fast memory layer that stores frequently used data close to the processor.' },
  { q: 'What is RAM?', a: 'Random Access Memory — fast, temporary storage that clears when power is lost.' },
  { q: 'What is a kernel?', a: "The core part of an operating system that manages hardware and system resources." },
  { q: 'What is concurrency?', a: 'Multiple tasks making progress during overlapping time periods.' },
  { q: 'Concurrency vs. parallelism?', a: 'Concurrency is managing many tasks at once; parallelism is running many tasks simultaneously.' },
  { q: 'What is a mutex?', a: 'A lock that ensures only one thread accesses a shared resource at a time.' },
  { q: 'What is Git branching?', a: 'Creating a separate line of development to work without affecting the main codebase.' },
  { q: 'What is a merge conflict?', a: 'When Git cannot automatically combine changes because they overlap.' },
  { q: 'What is a pull request?', a: 'A request to merge one branch into another, usually reviewed before accepting.' },
  { q: 'What is version control?', a: 'A system for tracking and managing changes to code over time.' },
  { q: 'What is CI/CD?', a: 'Continuous Integration/Deployment — automatically testing and shipping code changes.' },
  { q: 'What is unit testing?', a: 'Testing individual pieces of code in isolation to verify they work correctly.' },
  { q: 'What is a bug?', a: 'An error in a program that causes it to behave incorrectly.' },
  { q: 'What is debugging?', a: 'The process of finding and fixing errors in code.' },
  { q: 'What is refactoring?', a: "Restructuring code to improve its design without changing its behavior." },
  { q: 'What is technical debt?', a: 'The extra work created later by choosing a quick fix now instead of a better solution.' },
  { q: 'What is pseudocode?', a: 'An informal, plain-language description of an algorithm, not tied to any language syntax.' },
  { q: 'What is a syntax error?', a: "Code that violates a language's grammar rules and fails to run at all." },
  { q: 'What is a runtime error?', a: 'An error that occurs while a program is running, not at compile time.' },
  { q: 'What is exception handling?', a: 'A mechanism for catching and responding to errors without crashing the program.' },
  { q: 'What is a stack trace?', a: 'A report of the function calls active at the moment an error occurred.' },
  { q: 'What is machine learning?', a: 'Building systems that learn patterns from data instead of following fixed rules.' },
  { q: 'What is a neural network?', a: 'A model made of layered nodes, loosely inspired by the brain, used for pattern recognition.' },
  { q: 'What is encryption?', a: 'Converting data into a coded form that only authorized parties can decode.' },
  { q: 'What is a SQL injection?', a: 'An attack that inserts malicious SQL through unsanitized user input.' },
  { q: 'What is cross-site scripting (XSS)?', a: 'An attack that injects malicious scripts into pages viewed by other users.' },
  { q: 'What is a checksum?', a: 'A small value derived from data used to detect accidental changes or corruption.' },
  { q: 'What is Big O of insertion into a sorted array?', a: 'O(n) — elements may need to shift to make room.' },
  { q: 'What is a trie?', a: 'A tree structure optimized for storing and searching strings by prefix.' },
  { q: 'What is a heap (data structure)?', a: 'A tree-based structure where the smallest (or largest) element is always at the root.' },
  { q: 'What is Big O of heap insertion?', a: 'O(log n) — the element bubbles up through the tree height.' },
];
